config/routes.rb
Mm::Application.routes.draw do
  Blacklight.add_routes(self)
  HydraHead.add_routes(self)

  root :to => "catalog#index"

  devise_for :users

  resources :assets do
    resources :subjects, :only=>[:new,:create]
    resources :mmdbcore, :only=>[:new,:create]
  end
  
  match "assets/:asset_id/subjects/:subject_type/:index" => "subjects#show", :as => :asset_subject, :via => :get

  match "assets/:asset_id/mmdbcore/:node/:index" => "mmdbcore#show", :as => :asset_mmdbcore, :via => :get

  match "assets/:asset_id/subjects/:subject_type/:index" => "subjects#destroy", :via => :delete

  match "assets/:asset_id/mmdbcore/:node/:index" => "mmdbcore#destroy", :via => :delete
  

end

app/models/music_score.rb
# a Fedora object for the Music Score content type

class MusicScore < ActiveFedora::Base
  
  include Hydra::ModelMethods
  include Mmdb::ModelMethods

  has_metadata :name => "descMetadata", :type => Mmdb::MusicScoreModsDatastream
  has_metadata :name => "rightsMetadata", :type => Hydra::Datastream::RightsMetadata

  # adds file_objects methods
  include ActiveFedora::FileManagement

  delegate :title, :to => "descMetadata", :unique=>"true"
  
end

app/views/music_scores/_edit.html.erb
<%= render_submission_workflow_step -%>

<% unless params[:new_asset] %>
  <% sidebar_items << capture do %>
    <h3 class="twiddle">选择流程步骤</h3>
    <%= form_tag(url_for(edit_catalog_path)) do -%>
      <%= radio_button_tag(:wf_step, "titles") %> 标题 <br/>
      <%= radio_button_tag(:wf_step, "persons") %> 人物 <br/>
      <%= radio_button_tag(:wf_step, "genres") %> 分类/风格 <br/>
      <%= radio_button_tag(:wf_step, "files") %> 文件 <br/>
      <%= radio_button_tag(:wf_step, "permissions") %> 权限 <br/>
      <%= hidden_field_tag(:content_type,"music_score") %>
      <%= submit_tag("前往", :name=>"submit") %>
    <% end %>
  <% end %>
<% end %>

app/views/music_scores/_show.html.erb
<div class="document_viewer" id="cover_container">

	<h1 class="document-heading">
		<% unless get_values_from_datastream(@document_fedora,"descMetadata", [:title_info, :main_title]).first.empty? %>
	      <%= get_values_from_datastream(@document_fedora,"descMetadata", [:title_info, :main_title]).first %>
		<% else %>
			<%= params[:id] %>
		 <% end %>
	</h1>

  <h2 class="section-title">资源描述</h2>
  <div class="description">
   <%= display_field([:title],{:name=>'标题'}) %>
   <dt><label for="[:person]">人物</label></dt>
  <dd id="[:person]"><ul><%= display_fieldset(:person,{:name=>'标题'}) %></ul></dd>
    <%= display_field([:genre, :category],{:name=>'标题'}) %>
        <%= display_field([:genre, :primaryplayingform],{:name=>'演奏形式'}) %>
            <%= display_field([:genre, :secondaryplayingform],{:name=>''}) %>
            <%= display_field([:genre, :tertiaryplayingform],{:name=>''}) %>
                <%= display_field([:genre, :category],{:name=>'标题'}) %>
    <%= display_field([:genre, :primarygenres],{:name=>'体裁'}) %>
            <%= display_field([:genre, :secondarygenres]) %>
     <%= display_field([:abstract], {:name => '介绍'}) %>   
  </div>
  <%# copied to show_file_assets %>
	<% unless @document_fedora.file_objects(:response_format=>:solr).empty? %>
    <h2 class="section-title">资源文件</h2>
    <div class="uploads" id="uploads_<%= format_pid(params[:id]) %>">	
      <table id="file_assets" class="multipleEdit">
		    <tr>
		      <th></th>
		      <th>文件名</th>
		      <th>大小</th>
		      <th>添加时间</th>
		    </tr>
			<% @document_fedora.file_objects(:response_format=>:solr).each do |result| %>
  			<tr class="file_asset" >
  			  <% ext = result[solr_name("title", :text)].first.split('.').last %>
  			  <td>
  			  <% if ext == 'png' %>
  			  <%= tag("img", { :src => hydra_file_asset_path(result["id"]) }) %>
          <% end %>
          <% if ext == 'mp3' %>
            <%= tag("audio", { :src => hydra_file_asset_path(result["id"]), :controls => 'controls' }) %>',
          <% end %>
          </td>
  			  <td><%= link_to result[solr_name("title", :text)], hydra_file_asset_path(result["id"]) %></td>
  			  <td><%= result[solr_name("extent", :text)] %></td>
  			  <td>
  			    <% dt = DateTime.parse(result[ solr_name("system_create", :date)] ) -%>
  			    <%= format_date dt %>
  			  </td>
  			</tr>
			<% end %>		
		  </table>
  	</div>
	<% end %>

</div>